### ISSUE TITLE
Omnibox support

### ISSUE THREAD

**Issue by Madis0** [brandon1024/find#161]
I would really like to use this straight from Omnibox, without the need of using a popup. For activation you could for example use one of these keywords: `f` `find` `f+` `find+`.

Here are the APIs for [Chrome](https://developer.chrome.com/extensions/omnibox) and [Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/omnibox).

**Comment by brandon1024** [comment]
@Madis0 Great suggestion! I'm going to look into this.
