### ISSUE TITLE
Investigate Options Disabled by Default in Firefox

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#163]
## Issue Description
After installing the extension in Firefox, some of the features/options are disabled by default when they shouldn't be. This causes some confusion, and should be addressed.

**Comment by peter-kehl** [comment]
In Firefox 58.0.2, I don't see a way to use this at all. Ctrl+F doesn't match any regex. Firefox URL about:addons lists the add-on, but it doesn't let a user configure it.

**Comment by brandon1024** [comment]
@peter-kehl if you have questions about using the extension, I suggest you add a comment on the extension listing in the firefox addon store. The github issues are for development related bugs and improvements.

You can open the extension using `CTRL-SHIFT-F`. See [documentation](https://github.com/brandon1024/find/wiki/FAQ-:-General).

**Comment by peter-kehl** [comment]
Hi Brandon,

Thank you.

**Comment by jiberan** [comment]
Hi, is there any way to overide `CTRL-F` to invoke this extension in Firefox? Thanks.

**Comment by brandon1024** [comment]
No longer able to reproduce on develop. Closing issue.
