### ISSUE TITLE
Spacing adjusts when extension is opened

### ISSUE THREAD

**Issue by ekilah** [brandon1024/find#172]
## Issue Description
Website spacing is messed up when opening the extension.

## Steps to Reproduce
- I've only used the extension on one site, and it happened there: Crate and Barrel's wedding registration listing page (i.e.: create a wedding registry and view the items in your registry). 

## Screenshots and Documentation
http://www.giphy.com/gifs/3o7WIO2JCqmmCKrcRO

**Comment by brandon1024** [comment]
@ekilah Can you provide a link to the exact page you found?

**Comment by ekilah** [comment]
it's a private link for the registry I observed the issue on, which is why I described how to reproduce it yourself instead, hopefully it's not too prohibitive?

**Comment by brandon1024** [comment]
Ahh my apologies. I will look into this as soon as possible. Thank you for the feedback!

**Comment by brandon1024** [comment]
I have found the root cause of this issue. I should have fix in shortly 👍
