### ISSUE TITLE
Select matched text in Chrome

### ISSUE THREAD

**Issue by haroonis** [brandon1024/find#174]
## Issue Description
When searching with a regex that has many possilbe matches  - eg. [A-Z]{2} for 2 letters together - the matches are highlighted however not selected (to enable a quick and simple copy of the matched text) - is there a way to do this, i beleive it can be done with javascript but dont know how?

## Steps to Reproduce
Open search
Enter regex with unknown match

**Comment by brandon1024** [comment]
This issue wouldn't be simple to solve because some occurrences of a search could spread over multiple elements. Highlighting this text is difficult, and doing so in a way that doesn't cause issues with the orange highlight adds another layer of difficulty.

**Comment by haroonis** [comment]
Ok thanks for taking a look. Any idea how i could automate it given its some simple text i want to copy?

**Comment by brandon1024** [comment]
If I understand correctly, there are many occurrences of a regex on a page, and you want to extract those occurrences into another format?

I guess it depends on your programming ability. The way I would do it would be to clone this repository and modify the source so that you can console.log the occurrenceMap object. If you need help finding exactly where to add your code let me know.

**Comment by haroonis** [comment]
Yes they're all (shortish) text matches. I'll give it a try, I don't tend to use linux that much, more Windows to do the odd bit of C#. Thanks for the guidance, if you could let me know where to start with occurrenceMap I'll have a root around :)

**Comment by brandon1024** [comment]
That's fine, I typically develop this extension on a Windows machine anyway.

I would add a console.log(message.occurrenceMap) here https://github.com/brandon1024/find/blob/develop/content/highlighter.js#L14

This will cause the occurrenceMap to be logged with every update action. From here, you could write a small function that processes the map as you wish.

**Comment by haroonis** [comment]
Thanks Brandon, managed to get it working, at the expense of the scrolling working properly bizarrely! Appreciate the help
