### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [brandon1024/find#185]
hi you said 'Chrome Find-in-Page tool works well in most cases, but offers little when looking for specific (or general) keywords.'

could there please be a link to the github on the 'description' page of https://chrome.google.com/webstore/detail/find+-regex-find-in-page/fddffkdncgkkdjobemgbpojjeffmmofb

this would make it easy for most to find it

on this github page, could please make or link to a 'primer' for non-programmers

maybe with just some example of how to use this thing call 'regex'

like examples for 'specific' or 'general' words

on a normal page that most ppl see when using chrome would be helpful

so at least we can understand what this basically does

and how it basically helps

thank you

**Comment by brandon1024** [comment]
This repository is used for logging issues relating to the extension, like bugs and performance issues. It's better to leave feedback on the chrome extension listing feedback section.

This extension was designed for software developers. If you are having trouble using regular expressions, I recommend you visit [Regular Expressions - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions).
