### ISSUE TITLE
Persistent Highlights across tabs

### ISSUE THREAD

**Issue by maqwqa** [brandon1024/find#195]
It would be nice to have persistent highlights across tabs. After entering expression, highlights would also be applied for existing or new tabs (after switching tab).

Do you know if this is possible? I mean, not restricted by Firefox API, etc.?

**Comment by brandon1024** [comment]
@maqwqa Thank you for your input.

This feature would be possible, but I see few use cases. For now, I don't think this feature will be implemented, but thank you for your interest in the extension!
