### ISSUE TITLE
Not matching (AJAX?)

### ISSUE THREAD

**Issue by peter-kehl** [brandon1024/find#208]
Hi Brandon,

Thank you for Find+.

It doesn't match any word (for example: intelligent) from the main part of the following page: https://careers-travelclick.icims.com/jobs/2177/gms-res-developer---converted/job (or https://careers-travelclick.icims.com/jobs/intro?hashed=-435654145). The page content comes up delayed, possibly via AJAX.

**Comment by brandon1024** [comment]
This is happening because the main body of the web page is an iframe. Because of security limitations around XSS, highlighting in iframes is not possible. See this iss for more details: https://github.com/brandon1024/find/issues/155

**Comment by peter-kehl** [comment]
Hi Brandon @brandon1024,

How about indicating so to the user? If the page contains an <iframe> (and does it apply to frames, too?), then either
- indicate that the search can't cover the whole page (for example, change the colour of Find+ toolbar button), or
- disable search altogether for that page: disable the toolbar button (or show a crossed sign), and if the user presses Ctrl+Shift+F, show a warning instead of the search field, please.

That would save confusion.
