### ISSUE TITLE
Ctrl + Shift + F: Keyboard-Focus is not on the Search Textbox

### ISSUE THREAD

**Issue by schittli** [brandon1024/find#212]
**Thank you very much** for this very useful Extension!

## Issue Description
If we activate {find+} e.g. by pressing Ctrl+Shift+f, then the focus is not set to the {find+} textbox.

## Steps to Reproduce
- Press Ctrl+Shift+f
- Start typing a search expression - it will not work because the textbox does not have the focus

**Comment by brandon1024** [comment]
@schittli can you provide more details? I am unable to reproduce this issue.

Tested on:
Windows 10 Version: 10.0.17134 Build 17134, Chrome 69.0.3497.100 (Official Build) (64-bit)
macOS Mojave Version: 10.14, Chrome 69.0.3497.100 (Official Build) (64-bit)
