### ISSUE TITLE
Bug: search keywords are shared between incognito and normal windows

### ISSUE THREAD

**Issue by WoLpH** [brandon1024/find#213]
## Issue Description

Search keywords are shared between incognito and normal windows

## Steps to Reproduce
- open an incognito window
- search for something
- open a regular window
- the search field still shows the keywords from the incognito window

## Tasks
- prevent sharing of search keywords between (incognito)windows

**Comment by brandon1024** [comment]
Just a little note to myself for later: https://developer.chrome.com/extensions/extension#property-inIncognitoContext

To make sure that this the user is aware that their search history is discarded when in the incognito, we will display the warning icon when the property is detected.

**Comment by WoLpH** [comment]
I don't think it needs to be discarded completely. but separated between incognito and non-incognito windows would be nice :)

Beyond that I'm personally a big fan of the shared search across tabs, that works great!

**Comment by WoLpH** [comment]
Fantastic! Thanks for the quick response :)

**Comment by WoLpH** [comment]
I think the fix still has a few unfortunate issues.

The search input is still shared from incognito to regular windows, but not the other way around. And every time you switch tabs in incognito it clears the search field.

I'll see if I can fix it and create a pull request :)
