### ISSUE TITLE
 Broken on some pages

### ISSUE THREAD

**Issue by MartinLichtblau** [brandon1024/find#233]
## Issue Description
It searches and finds matches, but does not highlight or move to the location.

## Steps to Reproduce
goto https://autohotkey.com/docs/commands/Input.htm

**Comment by brandon1024** [comment]
The reason this issue is occurring is because the content of the page is embedded in an iframe. I have a wiki FAQ on this topic [here](https://github.com/brandon1024/find/issues/198).
