### ISSUE TITLE
Button on Google Adword pages  does not work

### ISSUE THREAD

**Issue by housepawsjohn** [brandon1024/find#234]
## Issue Description
A button that should fails to do anything when pressed.

## Steps to Reproduce
- Press such a button - in my case the google adword make a payment button.  It does nothing.  Nothing visible, no reaction, NADA
- Press Ctrl-Shift-F, then then button in step 1 works.
- Only found one such instance, will update with more as and if found.

**Comment by housepawsjohn** [comment]
It might have been browser (Firefox) weirdness or something else.  No issues the last time (two-three days ago) I went to make an adwords payment.

**Comment by brandon1024** [comment]
Great! Closing this issue.
