### ISSUE TITLE
Remember search position and query on page

### ISSUE THREAD

**Issue by WoLpH** [brandon1024/find#241]
## Issue Description
Not sure if this is an issue in other browsers, but in Chrome the extension loses the state completely as soon as it loses focus. So if you click on any part of the page you need to restart the search from the top.

It would be great if the script would store the current search state somewhere in the DOM of the webpage it was searching on, so it can continue the search where it left of.

## Steps to Reproduce
- Start searching for something using the extension in Google Chrome
- Click anywhere on the page
- Open the search extension again

The result is that it restarts as if it never searched before.

**Comment by brandon1024** [comment]
@WoLpH This could be a potentially challenging feature to implement. I think the best solution for this is to track in local storage the URL for the last web page the extension was open on, and the index. Then, when reopening the extension, load the data from storage and if the URL matches, set the index to that previous value.

**Comment by WoLpH** [comment]
I think you could do it far easier actually :)

The `content_scripts` are loaded on the page itself, unless you reload the page, their context stays. So if you store the state in that scope you should be fine.

The tricky part might be triggering the proxy to re-send the info.

**Comment by brandon1024** [comment]
@WoLpH Great suggestion, I hadn't thought about that! I'll have to adapt the content scripts to maintain a global index variable and pull that index into the background script when the extension loads. I prefer this solution far more 👍
