### ISSUE TITLE
Populate Search Field Option

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#272]
## Issue Description
Some users have recommended that instead of populating the search field with the latest item in the stored history, instead populate it with their most recent query. I can see a good use case for this. So, to support both ways, implement a new option in the options pane that so that the user can chose which option they prefer.

**Comment by SaltatorMortis** [comment]
my suggestion is simply another approach of this ticket:
keep the default behavior like now (most recent query)
and only if you pin one one multiple history entry(s) for a domain
it will select the last used of the pinned entrys for the currend domain
optionally a in the background loaded pinned entry doesn't get put on top of the history pile
