### ISSUE TITLE
Option to disable incremental search

### ISSUE THREAD

**Issue by mzso** [brandon1024/find#281]
## Issue Description
I've grown to really hate incremental search, because it scrolls all around the page randomly before I finish typing. It essentially scrolls to a random spot much of the time. I and I'm sure most people would want the next result for what they search for first and not a random one.

Searching only after pressing enter would be much preferred by me.

It's especially noxious on a website where with auto-loading of articles or other content, such as motorsport.com

## Steps to Reproduce
- type something in Find+.
- observe the pointless scrolling around before finishing typing what's intended.

(I'm aware the behavior matches FF, but it doesn't make it less problematic)

**Comment by brandon1024** [comment]
Hi @mzso. I just released version 2.1.0 which has improvements to the scrolling functionality. It should be easier to use now. Can you test it out and let me know what you think? It may take a few days for the updated extension to be published in the chrome web store.

**Comment by mzso** [comment]
[**@brandon1024**](https://github.com/brandon1024) commented on [2019. dec. 22. 21:27 CET](https://github.com/brandon1024/find/issues/281#issuecomment-568300465 "2019-12-22T20:27:43Z - Replied by Github Reply Comments"):
> Hi [@mzso](https://github.com/mzso). I just released version 2.1.0 which has improvements to the scrolling functionality. It should be easier to use now. Can you test it out and let me know what you think? It may take a few days for the updated extension to be published in the chrome web store.

What sort of improvements I should be looking for?

**Comment by brandon1024** [comment]
The page should only scroll if the next occurrence is not within the current viewport. This is closer to how Chrome's native find-in-page tool works.

**Comment by brandon1024** [comment]
Closing for now.

**Comment by mzso** [comment]
[**@brandon1024**](https://github.com/brandon1024) commented on [null](https://github.com/brandon1024/find/issues/281#issuecomment-570287244 "2020-01-02T17:56:04Z - Replied by Github Reply Comments"):
> The page should only scroll if the next occurrence is not within the current viewport. This is closer to how Chrome's native find-in-page tool works.

Well, I guess it helps, a bit.
