### ISSUE TITLE
Request: mark results, on seekbar.

### ISSUE THREAD

**Issue by mzso** [brandon1024/find#283]
## Issue Description

Not sure if it's possible with webextensions, but if it is I think it would be a much desired feature.
Colored the same color as the results are highlighted in the page.

**Comment by brandon1024** [comment]
Hi @mzso , thanks for your interest!

I looked into implementing this feature a while back, but ultimately decided not to for a few reasons. At the time, the API for implementing this was still considered experimental and I would have to worry about browser compatibility. Looking into it now, it looks like it hasn't changed much and Firefox doesn't appear to support it at this time.

[Details can be found here](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar).
