### ISSUE TITLE
Add option to search no matter of accents.

### ISSUE THREAD

**Issue by skanskan** [brandon1024/find#284]
Hello.

Your extension works very well.
But I would like to request for a new functionality: the ability to search words no matter of the accents.
Is it possible to do it now?

For example
ultimo would match ultimo, último, ultimó...
And there are many other accents... á à ü ñ...

We could call it, "accent insensitive".

**Comment by brandon1024** [comment]
Hi @skanskan ! Can you provide some example pages? In my testing, everything appears to work as expected.

**Comment by skanskan** [comment]
For me it doesn't work at any page with accents.

For example this page contains a classic poem:

https://www.poeticous.com/jose-de-espronceda/cancion-del-pirata?locale=es

I you search for the words **cancion** or **bergantin** it doesn't find anything.  You need to type exactly **canción** and **bergantín**

The native Chrome search function allows you to it, but not the find+ extension.
This option has two advantages, let's the user to find different variations and it's faster to type things without the accents.

> **Canción** del pirata
> Con diez cañones por banda,
> viento en popa a toda vela,
> no corta el mar, sino vuela
> un velero **bergantín**;
>  
> bajel pirata que llaman,
> por su bravura, el Temido,
> en todo mar conocido
> del uno al otro confín.
>  
> La luna en el mar riela,
> en la lona gime el viento
> y alza en blando movimiento
> olas de plata y azul;

**Comment by brandon1024** [comment]
This would be particularly tricky to implement. Right now, find+ supports 2000+ unicode characters which include most diacritical characters. To implement this feature, I would need go through each of these characters and pick their closest sibling character.

Furthermore, find+ is designed for extracting structured text from a page. If you need to match text in the way you described, the native functionality is likely your best bet.
