### ISSUE TITLE
Feature request: case-insensitive search

### ISSUE THREAD

**Issue by jasonbuechler** [brandon1024/find#285]
I skimmed through the code briefly but couldn't find the flexing muscle to try and kludge in a `//i` ... I'd be happy to submit a pull request and add the options-page functionality if someone could point me to the regex-match line(s)

Thanks
jason

**Comment by brandon1024** [comment]
Hi @jasonbuechler , find+ already supports this feature. It's an option in the options pane:
![image](https://user-images.githubusercontent.com/22732449/69914217-d1824400-1417-11ea-9e41-b970a9bdc292.png)

Just enable the 'Match Case' option!

**Comment by jasonbuechler** [comment]
Oh wow... I'm so blind it's tragic!
Sorry, and thank you for the polite help! :)

**Comment by brandon1024** [comment]
:-)
