### ISSUE TITLE
I put forward some suggestions

### ISSUE THREAD

**Issue by m1517** [brandon1024/find#286]
Hello, thank you for developing the plug-in, I put forward some suggestions

1. After the search box pops up, click the page search box to disappear. When searching for the next result, you need to search again, which is inconvenient. It is suggested that the search box be fixed on the page all the time

2. If the content of the page is too much, the search will fail. For example, the website: http://ffmpeg.org/ffmpeg-all.html

3. Can you remember the last shutdown word automatically by default under the same domain name?   ^_^

**Comment by brandon1024** [comment]
Hi @m1517, thanks for your interest in improving find+!

Unfortunately, these suggestions are limitations of browser extensions. Extensions are not permitted to stay open when the user clicks on the page.

Also, for large pages, the chrome extension has to do a lot of work to tokenize the page for quick lookup. For larger web pages, it's more appropriate to convert the web page to some form of unstructured text and parse it through other means.

I'm looking into your third suggestion now. We used to support this functionality, but some users found it to be confusing. I'll see if it's something I can bring back.
