### ISSUE TITLE
Save Expression Button NOT working since = Release Version 2.1.0 (public)

### ISSUE THREAD

**Issue by anteejay** [brandon1024/find#297]
## Issue Description
Save Expression button does not save expressions anymore

## Steps to Reproduce
- .1) Type a regular expression
- .2) Press Save Expression
- .3) Close the extension
- .3) Open the extension to find the saved expression not present

## Tasks
- [ ] t1
- [ ] t2
- [ ] t3

**Comment by brandon1024** [comment]
Thanks @anteejay , I'll look into this right away!
