### ISSUE TITLE
Add matched area previews

### ISSUE THREAD

**Issue by Madis0** [brandon1024/find#302]
## Issue Description
It would be nice to see clips of the page to see where the searched phrases are. Inspired by https://addons.mozilla.org/en-US/firefox/addon/find-in-page-with-preview/

## Steps to Reproduce
N/A

## Tasks
- [ ] Optional visual match previews in the popup

## Screenshots and Documentation
https://addons.mozilla.org/en-US/firefox/addon/find-in-page-with-preview/
https://github.com/YusukeTakeuchi/Find-in-Page-with-Preview

**Comment by brandon1024** [comment]
Thanks for your interest! There's already an open issue for this: #268 

I'm closing this as a duplicate.

**Comment by Madis0** [comment]
#268 is more like a extracted content piece, not a screenshot of the page area there. But I'm fine with either.
