### ISSUE TITLE
Page Down and Page Up break in User Guide

### ISSUE THREAD

**Issue by MarjaE2** [brandon1024/find#305]
## Issue Description
Page Down and Page Up break in User Guide

## Steps to Reproduce
- Open User Guide
- Page Down. At this point, it still works.
- Click in a subheading.
- Page Down. At this point it only moves within the heading. There's no way to move within a continuous, readable, keyboard-scrollable text.

**Comment by brandon1024** [comment]
When I implemented the user guide, I aimed for each section to be a scrollable pane but now that I think about it, it's probably better for the sections to extend to their full size. I'll address this in the next release.

**Comment by brandon1024** [comment]
Fixed in #321
