### ISSUE TITLE
Feature Requests: multiple simultaneous searches and highlight colors

### ISSUE THREAD

**Issue by Bamajon1974** [brandon1024/find#308]
How easy would it be to modify the code to allow for multiple simultaneous searches? For example, in the search box, enter multiple words separated by spaces or commas or line breaks and each word is highlighted in a different color? That would be a very useful feature. 

Also, can an option be added to change the highlight text color in addition to the highlight background color? It would make text stand out more depending on different background colors. 

Thanks in advance!

**Comment by brandon1024** [comment]
Hi @Bamajon1974 , thanks for your interest in Find+.

I don't see much usefulness for a feature like that, and it would be quite complex to implement. In that case, it might be best to save the page content in some format (html, rich text, etc) and use another tool. In what kind of situation do you find this feature would be helpful?

As for the text color, I've wanted to implement some sort of contrast scheme for text color that would automatically adjust the font color for best contrast. I'll look into this some more and see if I can come up with a solution.

Cheers!

**Comment by Bamajon1974** [comment]
Hi Brandon

Thanks for the reply.
Regarding multiple text search, this feature would be useful for searching
for multiple keywords or phrases in one go more for convenience than any
other reason. I don't know if regex search could accomplish the same goal
but I am not a coder and not versed in regex writing at all. I think there
are a couple of extensions on the Chrome store that would perform multiple
simultaneous keyword searches. However, I do like your idea of saving
webpages for off-line searches. Do you have any recommendations for
software that would perform the task? Plus, I am trying not to clutter up
Chrome with redundant extensions or too many extensions but searching
webpages is very important.

As far as options to configure background and text color, independently
configuring those options would be nice.

Thanks, Jon

**Comment by brandon1024** [comment]
@Bamajon1974  You can accomplish this effect through regular expressions. It might be best if you investigate regular expressions, since that's why this extension was created. [Here's some documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet). Specifically:
> x\|y
> Matches either "x" or "y". For example, /green\|red/ matches "green" in "green apple" and "red" in "red apple".

So you could match multiple patterns like this `(word)|(a phrase)|(a sentence)`

**Comment by Bamajon1974** [comment]
That trick to insert a vertical line between words, phrases, etc. works
perfectly for searching multiple terms. Thank you very much for your help!
I will keep a lookout for any additional customization feature additions.

Thanks, Jon

**Comment by brandon1024** [comment]
Created #311 in response to the text color contrast request. Closing this issue.
