### ISSUE TITLE
Each page shows 0 results on first try

### ISSUE THREAD

**Issue by alanghartJC** [brandon1024/find#309]
## Issue Description
For each page, the first time the find dialog is opened and searched, it doesn't find anything.
Closing and reopening the dialog will then find matches. This is **really** annoying, please fix. 

## Steps to Reproduce
- Open a new page in Chrome (on MacBook Pro, Catalina)
- Open the find dialog via the set key shortcut (Ctrl+f in my case)
- Type the text of something you see on the page
- No matches found
- Now close the dialog and reopen it
- Search for the same thing
- Results found this time

## Tasks
- .

## Screenshots and Documentation
![image](https://user-images.githubusercontent.com/37843366/73679148-11171780-4677-11ea-8c1b-bdafa790076e.png)
![image](https://user-images.githubusercontent.com/37843366/73679182-268c4180-4677-11ea-95ab-ab830e3da90b.png)

**Comment by sadmonad** [comment]
Same for me. It's weird bug I hope will be fixed soon :(

**Comment by brandon1024** [comment]
This was a particularly tricky one to fix, but I think I found the culprit. Will be opening a PR shortly :-) Sorry for the wait.
