### ISSUE TITLE
Really large page becomes unresponsive when I try to search

### ISSUE THREAD

**Issue by belousa** [brandon1024/find#310]

**Comment by brandon1024** [comment]
Could you attach more details? Link to the page, the regular expression you're using, and any other details would be helpful. Closing this issue for now, you can reopen once there's more details.

**Comment by belousa** [comment]
Here is a sample, very large file in Linux code. Typing anything in the search window never produces any finds. I can't quite repro the "unresponsive" part.

https://raw.githubusercontent.com/torvalds/linux/851ca779d110f694b5d078bc4af06d3ad37169e8/drivers/gpu/drm/amd/include/asic_reg/nbio/nbio_6_1_sh_mask.h

**Comment by brandon1024** [comment]
Yeah, this is not something that find+ is going to support. If you need to search through very large pages/files, it's more appropriate to use a more efficient tool (`grep`, an editor, etc).

**Comment by belousa** [comment]
Any way to mention this in ReadMe?
