### ISSUE TITLE
Better Highlight Color Contrast with Text Color

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#311]
## Issue Description
From #308 
> Also, can an option be added to change the highlight text color in addition to the highlight
> background color? It would make text stand out more depending on different background colors.
> 
> Thanks in advance!

I've wanted to implement some sort of contrast scheme for text color that would automatically adjust the font color for best contrast. I'll look into this some more and see if I can come up with a solution.

**Comment by Bamajon1974** [comment]
Thank you !
