### ISSUE TITLE
[Request] Option to disable OmniBox integration

### ISSUE THREAD

**Issue by SonOfDiablo** [brandon1024/find#312]
Hello,

I was wondering if it would be possible to add an option to disable the OmniBox integration?

I really like the extension, but I find it annoying that I have to go through extra steps if I want to use the OmniBox to make a Google search which starts with the word "find".
I haven't found a way to disable the integration through Chrome (under the search engine settings you can only disable the whole extension).

**Comment by brandon1024** [comment]
Hi @SonOfDiablo ,

I looked into this in a while back when another user asked a similar question, and determined that it is not possible to disable the Omnibox integration programatically.

One option is to change the omnibox keyword for the extension to `"find-ext"`, or similar, but there are a lot of users that use the Omnibox feature and it would be confusing to them if the keyword changed. If enough users want this change, then I'll implement it, but for now I'm going to keep the existing functionality.

Sorry :/

**Comment by SonOfDiablo** [comment]
I see, that is fair enough, didn't think it would be that difficult (but I haven't ever looked at what is possible with chrome extensions).

This might be a somewhat stupid followup question, but is it at all possible to change the keyword programatically as a setting in the extension? (I assume not since you didn't mention it).

In any way, I thank you for your response!

**Comment by brandon1024** [comment]
Yeah :/

That's not a stupid question, I wasn't very clear in my last comment. The extension omnibox features are defined through the extension's manifest file, which is static and can't be modified programmatically. This is what prevents me from modifying the omnibox behavior.

```
"omnibox": {
    "keyword" : "find"
  },
```

In reality, the omnibox API isn't very useful and it's a bit limited what you can do with it.

**Comment by SonOfDiablo** [comment]
Oh, right okay, I see now.

Thank kinda sucks :/
Well, nothing to do but crossing fingers for future improvements of the omnibox API I guess.

I appreciate your responses and explanations!
Gonna close this issue though as it seems like there is nothing to do about it and thus no need to keep this open.

**Comment by brandon1024** [comment]
Thanks for understanding! 👍
