### ISSUE TITLE
conflict with firefox reader mode hotkey / maybe add replace mode icon?

### ISSUE THREAD

**Issue by jakobi** [brandon1024/find#313]
## Issue Description
Ctrl-Alt-R is a firefox-internal shortcut reserved for firefox reader. 

Most pages do not offer a reader-reduced-cruft display, so I see some flicker on the top right as if something wants to present a large popup list, then the find-popup changes to  find-replace: Correct behaviour. 

What happens on a page that has an alternate "reduced-cruft" display however is this:

Page is re-rendered and changed (no flicker visible), popup remains open but can no longer match text (possibly reader-mode outputs something similar to a protected page a la mozext urls?).

Expected: Change find-popup to find-replace.

A second Ctrl-Alt-R now does change page again to original. Somehow find does see some of the hotkey and now displays find-replace, but again cannot match text. 

A partial workaround would be to offer an icon to switch to replace mode (all other modes have icons).

## Steps to Reproduce
- load https://www.storagereview.com/review/wd-red-4tb-hdd-review-wd40efrx
- press Ctrl-Shift-F to open find popup
- press Ctrl-Alt-R

**Comment by brandon1024** [comment]
Hi @jakobi , thanks for your interest! Adding a find-replace icon is easy enough, and has low impact to existing users who use the <kbd>^</kbd>+<kbd>Alt</kbd>+<kbd>R</kbd> shortcut. I'll implement this soon :-)

**Comment by jakobi** [comment]
Please see description of the bug in my comment in #331 - you seem off by the width of 1 icon, enabling icons shifts all icons and hides the start of any entered expression.
