### ISSUE TITLE
Won't scroll to result in plain text documents

### ISSUE THREAD

**Issue by andrebrait** [brandon1024/find#318]
## Issue Description

When opening a plain text document in Chrome (both from the hard drive and from the web), the search does return results, but going from one result to the next doesn't scroll the page until the result is on screen. 

## Steps to Reproduce
- Create a text document and type some big text in it
- Open it with Chrome
- Try to search for something in the document and see that scroll doesn't work
- Sometimes you have to reload the document of the search will fail completely (this is another bug, I think)

**Comment by Vulgum-Techus** [comment]
I have to open the extension once, then close it, then open it again, then it will make the search as requested. Getting pretty boring to do that each time :(

**Comment by brandon1024** [comment]
@andrebrait can you try the suggestion from @Vulgum-Techus ? This is a known defect right now, and I'm trying to fix it but it's proving more difficult than expected.

**Comment by brandon1024** [comment]
This should be fixed in the latest release, which should be available in the Chrome Web Store and Firefox Addons Store over the next few days. If the issue persists, feel free to reopen this issue. Cheers!
