### ISSUE TITLE
Still too bad app!

### ISSUE THREAD

**Issue by KSGTHB** [brandon1024/find#319]
## Issue Description
1. No  search history for user in app
2. No memory for last search if i search on different pages same text, i must input it each time. User must click on this app icon  on any page and see last search already in search string!!!
3. I see option "saved searches" but any  intuitive usability  how to do this and add needed to memory/

## Steps to Reproduce
- .
- .
- .

## Tasks
- [ ] t1
- [ ] t2
- [ ] t3

**Comment by brandon1024** [comment]
@KSGTHB Please create three separate issues with full descriptions and steps to reproduce. Thanks.
