### ISSUE TITLE
"Feature" request: an extension for searching number ranges on the page

### ISSUE THREAD

**Issue by Joshfindit** [brandon1024/find#320]
## Description

`find+` is awesome and has served well for many things, but what I was really looking for when I found it is something that lets me do things like:

- `x >= 100`
- `3 <= x <= 22`
- `x = $45.00..$60.99` *This one would be awesome, but probably extremely difficult to implement. Helps avoid matching junk when looking at store listings.

Note: I was going to put more examples, but now with `find+`, I realize I'm probably almost always going to be searching for numbers, especially on ecommerce stores

**Comment by brandon1024** [comment]
All of these can be accomplished using regular expressions, you just have to get a bit creative. Maybe have a look [here](https://www.w3schools.com/jsref/jsref_obj_regexp.asp).

- `^\d{3,}$`
- `^([3-9])|(1\d)|(2[0-2])$`
- `^\$(4[5-9]\.\d\d)|(5\d\.\d\d)|(60\.\d\d)$`

**Comment by Joshfindit** [comment]
Oh certainly. regex can essentially accomplish anything, but it’s cumbersome for numbers, and un-glanceable for anything mildly complex.

I certainly respect your preference for regex so I won’t push it.
But if you ever decide to put in a “numbers” mode, I’m there 🚀
