### ISSUE TITLE
Using Enter to search second time doesn't work

### ISSUE THREAD

**Issue by Hemloc** [brandon1024/find#325]
## Issue Description
After you have performed a search for something, then close and reopen the search bar, the previous search text is still there, and if you press Enter, nothing happens. No results are returned, not even zero.

It would also be nice if after pressing Enter for the second search it continued from the current position, but Issue 323 was opened for that :)

## Steps to Reproduce
- Open search bar using Ctrl+Shift+F.
- Enter any text.
- Press ESC.
- Open search bar again using Ctrl+Shift+F.
- Press Enter.

**Comment by brandon1024** [comment]
Fixed! Will be opening a PR shortly.
