### ISSUE TITLE
How to continue after popup closed for whatever reason

### ISSUE THREAD

**Issue by hopalongrock** [brandon1024/find#335]
## Issue Description
How to continue the search after the popup is closed.
For example it is closed when save screen with Greenshot.
When I reopen the pop-up window, it remembers to the previous text, but it doesn't work. Currently I modify and undo the modification to make the original search work again.
Is there an easier way to do this?
## Steps to Reproduce
- .
- .
- .

## Tasks
- [ ] t1
- [ ] t2
- [ ] t3

## Screenshots and Documentation
original find:

![20201118 095217  Release _ Notepad++ 7 9 1 Released _ Notepad++ Community — Mozilla Firefox](https://user-images.githubusercontent.com/6840865/99508577-09fe9300-2985-11eb-9f09-7bc0f280fd19.jpg)

this is after new Ctrl Shift F, find is not active

![20201118 095737  Release _ Notepad++ 7 9 1 Released _ Notepad++ Community — Mozilla Firefox](https://user-images.githubusercontent.com/6840865/99509203-c0fb0e80-2985-11eb-9cf8-9483529bbcfc.jpg)

If I write a space after ruined and  press backspace, the find works again as originally.

**Comment by brandon1024** [comment]
This is an existing bug, and is currently fixed on the develop branch but hasn't yet been released. This fix will be released soon.

**Comment by hopalongrock** [comment]
Great!
