### ISSUE TITLE
First time using find+ via keyboard on each page does not work

### ISSUE THREAD

**Issue by favorini** [brandon1024/find#340]
## Issue Description
First time using find+ via keyboard (ctrl-shift-f) on each page does not work. Second time works. Clicking the toolbar button works the first time. This is on Chrome and Edge using find+ version 2.1.1.

## Steps to Reproduce
- Visit any web page
- Press ctrl-shift-f
- Type a search pattern
- No matching text is highlighted. The search up and down arrows remain greyed out.
- Hit Esc
- Press ctrl-shift-f
- Type a search pattern
- Now it works

## Screenshots and Documentation
Not sure if this is related: When you have a previously entered search pattern, it shows up in the search box, but you cannot search the page just by hitting Enter. You have to add or delete a character and then hit enter. Kind of annoying.

**Comment by brandon1024** [comment]
A fix was merged a while ago and will be available in the next version 2.2.0, which is currently in review by Google.
