### ISSUE TITLE
Stopping the background process once bricks the extension forever

### ISSUE THREAD

**Issue by Shulcare** [brandon1024/find#341]
## Issue Description
I was playing around a bit and stopped the background process that find+ needs. Obviously it didn't work anymore. But now I'm stuck as there is no way to activate this process again.
De- and reinstalling find+ did not start it. Even if I close the brower and reboot Windows in between, installing it did not start the process anew. I couldn't find anything about manually starting this in the internet. The find+ documentation does not mention this process in any way, either.
It seems this extension is now bricked on my machine for all eternity... Which is a pity because it got much better search results than any other extension I've tried!

## Steps to Reproduce
- Deactivate the background browser process that has been started by installing find+.

## Tasks
- Please add a description how to activate the process if it has been closed by whatever reason.

**Comment by brandon1024** [comment]
@Shulcare how do you stop the background process? I've never seen that happen before. Can you provide specific steps to reprodeuce?

Thannks!

**Comment by Shulcare** [comment]
Hi,
Well, I can only describe it roughly from my memory as I obviously cannot reproduce it now... :-)

Installation of find+ added a tray icon of my browser to the taskbar. (BTW: I'm using Vivaldi, Chromium-based.) When I clicked on this, I saw a few menu items. One was something about find+, one was an Autostart option, and then something else (can't remember exactly).
I think I clicked on the Autostart item which probably disabled the Browser process autostart entry in Windows. Then this tray icon vanished, the Vivaldi autostart entry was removed (checked with Task-Manager Autostart tab), and no way to get it back. The browser preferences don't show anything about an autostart or background.
Maybe this is a Vivaldi-specific problem, I don't know...

**Comment by brandon1024** [comment]
@Shulcare, this is an odd one and I'm not sure I can be of much help. This sounds more like an issue with the browser you're using than the extension itself. There's not much I can do from a development point of view. You might want to log a defect with Vivaldi.

**Comment by Shulcare** [comment]
OK, strange... Thanks anyway for your time! Maybe I'll try a complete browser un&reinstall some time when I'm motivated enough.

**Comment by brandon1024** [comment]
Thanks for using Find+!
