### ISSUE TITLE
Why is this extension asking permission to "access your-data-for-all-websites" ?

### ISSUE THREAD

**Issue by mauriciogracia** [brandon1024/find#351]
## Issue Description

Why is this extension asking permission to "access your-data-for-all-websites" since it could used "Read the text of all open tabs" ?

Some reviews of the extension are concerned that the plugin might be accesing to user/password details

Is that permission required for a particular reason, or is there something that could be done ?

**Comment by brandon1024** [comment]
Hi @mauriciogracia, thanks for your interest! I've answered this question over in #338, so I'll link to that answer:

https://github.com/brandon1024/find/issues/338#issuecomment-794367631

**Comment by mauriciogracia** [comment]
Great answer, thanks
