### ISSUE TITLE
Chrome extension link doesn't work for me

### ISSUE THREAD

**Issue by yannicklerestif** [brandon1024/find#358]
## Issue Description
I can't access the extension page from the readme file: [https://chrome.google.com/webstore/detail/find%2B/fddffkdncgkkdjobemgbpojjeffmmofb](https://chrome.google.com/webstore/detail/find%2B/fddffkdncgkkdjobemgbpojjeffmmofb) (I get a 404 error)

## Steps to Reproduce
Click the link above

## Screenshots and Documentation
![image](https://user-images.githubusercontent.com/5543284/132000041-e338d476-c831-41aa-91dc-49722e44ccb0.png)

**Comment by pzhlkj6612** [comment]
In chrome://extensions/?id=fddffkdncgkkdjobemgbpojjeffmmofb , Chrome reports:

> ⚠️ This extension violates the Chrome Web Store policy.

**Comment by brandon1024** [comment]
The extension will be back online at some point soon. I need to upload a privacy policy to GitHub to prove that I don't handle personal data.

**Comment by pzhlkj6612** [comment]
Good to know this. Thank you for your hard work.

**Comment by pzhlkj6612** [comment]
The Chrome web store link works. Thank you @brandon1024  .
