### ISSUE TITLE
How to replace parantheses?

### ISSUE THREAD

**Issue by Aybee** [brandon1024/find#367]
## Issue Description
I've tried to replace parantheses with `$1` ... But it doesn't work. Didn't you implement this or am I doing it the wrong way?

## Steps to Reproduce
Search for` (g)oo(gle)`
Replace with `$1ii$2`
Result should be `Giigle`
Result is `$1ii$2`

**Comment by brandon1024** [comment]
Capture groups aren't supported yet. This sounds like a duplicate of https://github.com/brandon1024/find/issues/362.

**Comment by Aybee** [comment]
Thank you, then I would like to look at this as a Feature Request.
