### ISSUE TITLE
Popup Input Field Request Focus and Text Select on Load

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#37]
As it stands, when the extension is launched by using keyboard shortcuts or by clicking the browser action, the  search input field does not request focus, requiring the user to click the extension to input text. The text in the field should also become selected once the extension loads.

Saving the previous search will be fixed in a separate issue: https://github.com/brandon1024/find/issues/40

**Comment by MikeWalz11** [comment]
Will find an appropriate place to add the fix:

window.onload = function() {
  document.getElementById("searchField").focus();
};

**Comment by brandon1024** [comment]
Not only should the search field request focus, it should also select any text that is in the input field.

**Comment by MikeWalz11** [comment]
@brandon1024 not sure if I understand the wording of your last comment, but do you mean if I have something highlighted, and press ctrl+shift+f, it will appear in the search bar?

**Comment by MikeWalz11** [comment]
@brandon1024 pertaining to my last comment, I understand now.  As it stand, it the input field "value" maintained after the extension is closed?  If not will need to save last input, then select as you suggest...

**Comment by brandon1024** [comment]
@MikeWalz11 I'll try to elaborate a bit better. In your second comment, you did bring up a point that I hadn't actually considered.

So if I press `ctrl-f` and type something into the search field, and I were to press `ctrl-f` again, the text in the search field should become selected. Also, like you said, the previous search query should be stored and inserted into the search field when the extension loads.

Now, that will be a bit more challenging because all scripts are unloaded when the extension closes. We will need to use the `chrome.storage API` for that. Wouldn't be a big problem though.

Should these changes all be wrapped under this issue? I'm fine if it is.

**Comment by MikeWalz11** [comment]
Will use to save last user input upon close: https://developer.chrome.com/extensions/storage

**Comment by MikeWalz11** [comment]
@brandon1024 lol didnt see your comment about chrome api till after I found it on stackOF.  I will cover everything talked about in this issue.  All the required changes seem very minor.

**Comment by brandon1024** [comment]
@MikeWalz11 I decided to separate the storage part of this issue. That will be fixed in https://github.com/brandon1024/find/issues/40 :)

So in this issue, all we will need to do is make the search text field request focus when the popup is opened, and ensure that text in the field (there won't be any for now, but will be once the aforementioned issue is fixed) is selected/highlighted.

We will fix this issue first, and then after that, we will fix https://github.com/brandon1024/find/issues/40.

**Comment by brandon1024** [comment]
@MikeWalz11 was this fixed in the recent F37 merge?

**Comment by MikeWalz11** [comment]
@brandon1024 #40 and #37 are now both resolved from Previous PR

**Comment by MikeWalz11** [comment]
Resolved in PR: #43
