### ISSUE TITLE
Incorrect regex in the User Guide

### ISSUE THREAD

**Issue by michaelts1** [brandon1024/find#375]
## Issue Description
In the "User Guide" page that opens after installing the extension, it says:
> Find+ supports any regular expression supported by JavaScript
...
The following example matches any quoted date with the format "####-##-##".
>> "\d{4}-\d{2}-\d{d}"

However, `{d}` is not a valid quantifier in JavaScript, and is interpreted as the literal string `"{d}"`. For example, the above regex will match `"2012-10-1{d}"`, but not `"2012-10-17"`.
I assume that this is a mistake and the intended text was `"\d{4}-\d{2}-\d{2}"`, and will be happy to send a PR if this is actually the case.

## Steps to Reproduce
- Install the extension
- Read the "User Guide" page that opens

## Screenshots and Documentation
![Screenshot_1](https://user-images.githubusercontent.com/41857330/153751780-8bd27ff6-40cd-425f-9cb6-40ab26914cce.png)
You can confirm this is incorrect by going to https://regexr.com/6fb4h

**Comment by brandon1024** [comment]
Ahh yes, you're correct. Good catch! If you want to submit a PR, I will happily merge :-)
