### ISSUE TITLE
Find+ port to Microsoft Edge

### ISSUE THREAD

**Issue by Guycicle** [brandon1024/find#383]
Hi there,

I'm a big fan of your extension find+ and use it daily for my work. Unfortunately, I can no longer use chrome for work and I was wondering if you would be able to port this extension to Microsoft Edge? It would be a huge help!

I found an article on how to, it looks to be quite simple: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension

Many thanks

**Comment by pzhlkj6612** [comment]
Hi, maybe you can directly install this extension on Microsoft Edge. I tried this and it works: "Add an extension to Microsoft Edge from the Chrome Web Store" in [Add, turn off, or remove extensions in Microsoft Edge](https://support.microsoft.com/microsoft-edge/9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026).

### Screenshots for negative lookbehind regex in Microsoft Edge 103.0.1264.71 on Windows 10

- [Add, turn off, or remove extensions in Microsoft Edge](https://support.microsoft.com/microsoft-edge/9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026):

![20220730-081120-Microsoft_Edge_103_0_1264_71-Find_+-extension-Google_Chrome_Web_Store](https://user-images.githubusercontent.com/29089388/181862389-649f67ba-06db-4c0c-8b5c-5089ee9c1829.png)

- [HTML5test - How well does your browser support HTML5?](https://html5test.com/):

![20220730-081556-Microsoft_Edge_103_0_1264_71-Find_+-extension](https://user-images.githubusercontent.com/29089388/181862538-a86afd9c-e1d0-4504-98a7-54e4e285b07f.png)

**Comment by brandon1024** [comment]
@Guycicle can you give @pzhlkj6612 's suggestion a try and report back? Thanks!

**Comment by Guycicle** [comment]
Very sorry for the late reply.

Mozi's solution of installing the extension via Chrome store on Edge
browser did work. I never even thought to give this a try!

Many thanks, you have made my work life a lot easier.

**Comment by brandon1024** [comment]
@Guycicle glad to hear it! Cheers :beers:
