### ISSUE TITLE
no results in any page I've tried since installing

### ISSUE THREAD

**Issue by scotthz** [brandon1024/find#387]
## Issue Description
When I search using this extension, no results are found and highlighted.

Installed on:
  Macbook Pro M1 Pro
  macOS 12.6 (21G115)
  Chrome 105.0.5195.125

## Steps to Reproduce
- Use keyboard shortcut to activate find+.
- Verify that the search text box that drops down from the extension icon is find+ by noting that clicking on the wrench icon displays the find+ configuration UI.
- Enter plaintext that matches visible text content on the current page but doesn't use any regex syntax.
- Observe that matching text is not highlighted.
- Examples
  - Search for _remote_ on <https://git-scm.com/docs/git-pull>
  - Search for _follow_ on <https://support.typora.io/Markdown-Reference/#fenced-code-blocks>

## Screenshots and Documentation

**Active find+ search text box and config UI** 
![image](https://user-images.githubusercontent.com/8260639/191315270-26a48301-d05a-454e-99e2-8323b82c27a9.png)

**First example above:**
![image](https://user-images.githubusercontent.com/8260639/191317957-d5a75d44-0b3b-4cb3-ab1c-ebd7fc6d4450.png)

**Comment by brandon1024** [comment]
Works fine for me:

![image](https://user-images.githubusercontent.com/22732449/191325655-693ee911-e69a-4512-a3e4-c8b29df47d2e.png)

Can you try reloading the page and try again?

**Comment by scotthz** [comment]
Thanks for your response.

Sorry for the delayed followup. Reloading the page didn't change anything for me. Following a couple Chrome updates it's working for me now  on most pages. I found that it fails on the local Find+ user guide page. On my machine that's chrome-extension://fddffkdncgkkdjobemgbpojjeffmmofb/docs/index.html. No error message but I'm guessing that is due to the same constraint on chrome:// URIs even though the namespace is not an exact match (screenshot below). 

This issue should be closed.

Regards, Scott

![image](https://user-images.githubusercontent.com/8260639/198308459-837fe81b-74a7-49bd-9069-bf439ed303a5.png)
