### ISSUE TITLE
Regex Incorrectly Sent to Background Script

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#39]
While debugging https://github.com/brandon1024/find/issues/9, I noticed that the wrong regex is being sent to the background script. Upon further investigation, I believe I have discovered the cause. When the `onInput` event is fired, a message is sent via the Message API through our flow. My guess is that when the event is fired, the text in the search field still has not been updated, causing the JSON payload to have invalid information.

If this is the case, introducing a small delay would _fix_ this, but this isn't exactly desired because this would introduce a race condition between our Message API and the HTML/JS.

**Comment by brandon1024** [comment]
Will await https://github.com/brandon1024/find/issues/9 before fix

**Comment by MikeWalz11** [comment]
Is the 'on input' event triggered by keypress?  If so I eliminated an issue earlier by triggering an event after-keypress insead of on-keypress

**Comment by brandon1024** [comment]
Yeah the event is triggered by a keypress: `document.getElementById('searchField').addEventListener('keypress', updateHighlight);`

This issue is low priority until issue #9 is merged :)

**Comment by brandon1024** [comment]
Resolved in F9.
