### ISSUE TITLE
Inputfield is black and font color also

### ISSUE THREAD

**Issue by Aybee** [brandon1024/find#390]
## Issue Description
I wondered, why suddenly the whole input dropdown was black, but I found the reason.

![Screen-2022-12-14_00-54-52](https://user-images.githubusercontent.com/1143013/207471377-e08f8da4-4597-4f8b-8f14-cf086edd6fd8.png)

## Steps to Reproduce
It depends on the setting of my Firefox. Happens, when I uncheck this checkbox:

![Screen-2022-12-14_00-49-37](https://user-images.githubusercontent.com/1143013/207471170-f1048c47-0303-4eea-a862-5f7ea59a161f.png)
It might be related to this error here: https://github.com/brandon1024/find/blob/4795d28b22fd98681199e2295e8efe7bfbb8df78/docs/help.css#L49-L56
If you set a `background-color`, then you need to make sure you set a `color` as well. You cannot rely on the user setting white as the background color and black as the foreground color. This makes the help page also not readable for me.

![Bildschirmfoto am 2022-12-14 um 00 56 06](https://user-images.githubusercontent.com/1143013/207472790-299a745d-63b5-4400-afb1-9e0ef240fde9.png)

**Comment by brandon1024** [comment]
Hey! Thanks for your interest in find+. I'm pretty hands off these days, but will happily merge any pull request for this.

**Comment by Aybee** [comment]
Yes, it's a shortcomming that Firefox has no integrated regex-search, that's why I've been interested in find+ for a long time.

I'm a webdeveloper but unfortunately I've no time to figure out how to develope browser addons. I'm pretty good at CSS, HTML and JS. Maybe if I find the time I can take a look at the help files `help.css` and `index.html` if that would help.

If you tell me where I can find the CSS for the search box and how to debug it, I can also take a look at this.

**Comment by brandon1024** [comment]
Most of the CSS for the popup is [here](https://github.com/brandon1024/find/blob/develop/popup/css/extension.css). The CSS for the help page is [here](https://github.com/brandon1024/find/blob/develop/docs/help.css). Check out [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing) for testing extensions.

**Comment by brandon1024** [comment]
Fixes will be available in the upcoming release, version 2.2.3 :tada:
