### ISSUE TITLE
darken this

### ISSUE THREAD

**Issue by davidp88** [brandon1024/find#392]
Pls darken this,can't even see it.

![find](https://user-images.githubusercontent.com/80623401/212546137-ae309aee-1de6-4eaa-8237-b7b4a208a5f7.jpg)

**Comment by Aybee** [comment]
Related https://github.com/brandon1024/find/issues/390

**Comment by brandon1024** [comment]
Fixes will be available in the upcoming release, version 2.2.3 :tada:
