### ISSUE TITLE
Add icon and/or menu item to open {find+}

### ISSUE THREAD

**Issue by liamquin** [brandon1024/find#398]
Unfortunately this isn't the only extension i have that wants to use control-shift-f.

How about a toolbar icon, and/or Edit->Find with {Find+}, so that the add-on can be used without the keybinding?

**Comment by brandon1024** [comment]
The shortcut can be freely assigned in Chrome and Firefox. The steps to do this in Chrome are documented in the help pages, the steps for Firefox are [here](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox).

This extension is used by a lot of people and I worry that changing the default shortcut will frustrate a lot of people. If there's more interest in this, maybe I'll revisit.

**Comment by liamquin** [comment]
Thanks - i was not trying to suggest changing the default shortcut -
you can't ever guarantee it's not already in use and control-shift-f
seems like a good choice.

But i thought maybe adding an icon and/or menu item as an additional
way to access it might be useful.

-- 
Liam Quin, https://www.delightfulcomputing.com/
Available for XML/Document/Information Architecture/XSLT/
XSL/XQuery/Web/Text Processing/A11Y training, work & consulting.
Barefoot Web-slave, antique illustrations:  http://www.fromoldbooks.org
