### ISSUE TITLE
Save Last Input and Highlight

### ISSUE THREAD

**Issue by MikeWalz11** [brandon1024/find#40]
Whenever the extension is closed, we will want to maintain the previous value in the input field.  Upon re-opening the extension, the last value should be highlighted and the input field in focus.

**Comment by brandon1024** [comment]
See my comment [here](https://github.com/brandon1024/find/issues/37#issuecomment-294937109). This issue will follow https://github.com/brandon1024/find/issues/37

**Comment by brandon1024** [comment]
Fixed: https://github.com/brandon1024/find/pull/43
