### ISSUE TITLE
latest beta

### ISSUE THREAD

**Issue by davidp88** [brandon1024/find#401]
where to get the latest beta of it

**Comment by strazto** [comment]
everything post https://github.com/brandon1024/find/tree/v2.2.2 looks unreleased, technically you build it yourself and install it, although that doesn't sound very fun

**Comment by pzhlkj6612** [comment]
after checking out code from the tree, you can directly load it to your browser:

- Chrome: [Loading an unpacked extension § Chrome Extension development basics - Chrome Developers](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked).
- Firefox: [Temporary installation in Firefox | Firefox Extension Workshop](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/). Don't forget to rename "manifest_firefox.json" to "manifest.json".

**Comment by brandon1024** [comment]
That's correct, you just need to checkout the project and load the extension in the browser. You don't need to build a release archive. Follow the links that @pzhlkj6612 provided.

Cheers!
