### ISSUE TITLE
{find+} extension in Firefox addon store is corrupt

### ISSUE THREAD

**Issue by Bamajon1974** [brandon1024/find#406]
## Steps to Reproduce
- Reloaded webpage, installation produced the same error
- Restarted Firefox, installation produced the same error

## Tasks
Please re-upload latest version to Firefox store

## Screenshots and Documentation
![find+](https://github.com/brandon1024/find/assets/48393602/cb03a203-4c42-472f-816f-1cabe5aa2d20)

**Comment by Bamajon1974** [comment]
(Bump)

**Comment by brandon1024** [comment]
I'm not able to reproduce what you're seeing. Installs just fine in my environment, I haven't seen anyone else have issues like this.

What version of firefox are you using?

**Comment by Bamajon1974** [comment]
Thank you for the reply. Firefox v121 but started with v120. I restarted Firefox without add-ons, same corruption error message when installing {find+} extension. I cleaned the Firefox cache, same corruption error message when installing {find+} extension. I refreshed Firefox, same corruption message when installing {find+} extension. However, when I completely uninstalled Firefox, deleted all Mozilla directories in %appdata%, %programdata% and %programfiles% folders and reinstalled, I was able to install {find+} without error. 

Before refreshing, the original profile folder was saved automatically by Firefox. Is/are there log files with the configuration that would be useful? 

I imagine some sort of customization or add-on caused the issue. I had several changes in about:config and applied some custom css code in userChrome.css and userContent.css files to make the titlebars colored and remove the Recommendations section on the Add-ons page. 

However, I wonder if the culprit was trying to install TabMixPlus as a legacy extension. Check out the webpage, https://github.com/onemen/TabMixPlus, particularly the multiple steps needed to get this addon working. Do you think that might be the culprit? 

Thanks!

**Comment by brandon1024** [comment]
I'm not too sure why you ran into issues like this, but it sounds environmental and not a problem with the extension itself. If anyone runs into this we can re-open.
