### ISSUE TITLE
Add 'Enter', 'Shift+Enter', and `Ctrl+Enter Actions

### ISSUE THREAD

**Issue by MikeWalz11** [brandon1024/find#45]
Once the highlighted DOM is set, pressing 'Enter' should proceed to the next valid search, while pressing 'Shift+Enter' should proceed to the previous.
Additionally, pressing 'Ctrl+Enter' should close the extension.

**Comment by brandon1024** [comment]
Fixed: https://github.com/brandon1024/find/pull/53#pullrequestreview-35503972
