### ISSUE TITLE
Refactor occurences of 'onkeypress' & 'onkeyup' to 'input'

### ISSUE THREAD

**Issue by MikeWalz11** [brandon1024/find#46]
For updating the highlighting, and storing of current SearchField text, both 'onkeypress' & 'onkeyup' will not be invoke an event listener in the case of selecting predictive text, or copy+paste. 

On the other hand, changing the SearchField event listener to be sensitive to 'input' simply catches all changes to the input field.  This can simply be done in any outstanding feature branches, and implemented moving forward.

- [x] F37_InputFocusAndSave
- [x] F9-Build-Backend-DOM-Search

**Comment by brandon1024** [comment]
Resolved in F9. Can we close this issue?

**Comment by MikeWalz11** [comment]
Resolved in both F9 and F37 feature branches.
