### ISSUE TITLE
Add Dynamic Width to search bar

### ISSUE THREAD

**Issue by MikeWalz11** [brandon1024/find#50]
On wider monitors, the normal ctrl+f tool will become much wider than our original sizing.  
Can either add 1 or 2 @media .css changes to increase bar width depending on screen size, or make dynamic for all screens with using 'em' instead of 'px'.

**Comment by brandon1024** [comment]
@MikeWalz11 any way you can add images? I can't replicate it :(

**Comment by MikeWalz11** [comment]
Won`t Fix
