### ISSUE TITLE
HTML Entity Decoding

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#64]
Beta Fix: While testing the extension on Wikipedia, I noticed that the whitespace character `&nbsp;` appeared often in the DOM, which made searching more difficult.

We should add support for treating these entities as simple characters so that the regex search engine can do its magic. We should provide support for ASCII characters only, all other characters can be interpreted by their entity name when needed in the search.

So, entities between `&#32;` and `&#126;` should be treated as their respective character representations. We will NOT support ISO-8859-1 characters and symbols, or any other miscellaneous symbols.

An option should also be available to ignore html character entities, i.e. treat their codes as characters themselves.

**Comment by MikeWalz11** [comment]
PR Merged #70
