### ISSUE TITLE
Webpage Not Restored Properly

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#71]
While testing the extension, I noticed that some of the markup that we inject into the webpage is not removed correctly. This occurs when our markup does not contain any children nodes. The reason this occurs is because the jquery function `.contents()` will return an empty jQuery object when an object does not contain any children nodes. Performing an `unwrap()` on this object will have no effect.

This issue surfaced after an earlier fix: https://github.com/brandon1024/find/pull/70/files#diff-ce3bdf8c52716d2048208c2ad1279742R130

To be addressed:
- If our markup does not have any children nodes, it should be removed correctly in our `restore()` function

**Comment by MikeWalz11** [comment]
PR Merged #72
