### ISSUE TITLE
Scrolling to Text In Footer

### ISSUE THREAD

**Issue by brandon1024** [brandon1024/find#79]
When text is highlighted in the footer of a page (in the bottom 100px of the page), our `seekHighlight` function scrolls slightly above it, which hides it. Originally, this was done to ensure that highlighted text appears 100px down from the top of the client window and to ensure that text doesn't appear behind a webpage top banner.

Currently, in `seekHighlight`, `window.scrollBy(0,-100);` is executed regardless of where the text is in the page. However, if a highlight appears in the bottom of the page, this should not be executed.

**Comment by MikeWalz11** [comment]
PR Merged #80
